const mongoose = require('mongoose');
const dotenv = require('dotenv');
const connectDB = require('./config/db');
const GameItem = require('./models/GameItem');

dotenv.config();

const gameItemsData = [

// ==========================================
  // 0. СИСТЕМНЫЕ ЗВУКИ (UI И ИНТРО)
  // ==========================================
  { itemId: 'sys_stage_1', type: 'system', text: '1-Кезең', audioPath: '/audio/system/stage_1.mp3' },
  { itemId: 'sys_stage_2', type: 'system', text: '2-Кезең', audioPath: '/audio/system/stage_2.mp3' },
  { itemId: 'sys_stage_3', type: 'system', text: '3-Кезең', audioPath: '/audio/system/stage_3.mp3' },
  { itemId: 'sys_stage_4', type: 'system', text: '4-Кезең', audioPath: '/audio/system/stage_4.mp3' },
  { itemId: 'sys_stage_5', type: 'system', text: '5-Кезең', audioPath: '/audio/system/stage_5.mp3' },
  { itemId: 'sys_game_start', type: 'system', text: 'Ойын басталды', audioPath: '/audio/system/game_start.mp3' },
  { itemId: 'sys_game_end', type: 'system', text: 'Ойын аяқталды', audioPath: '/audio/system/game_end.mp3' },
  { itemId: 'sys_delete', type: 'system', text: 'Өшіру', audioPath: '/audio/system/delete.mp3' },
  { itemId: 'sys_check', type: 'system', text: 'Тексеру', audioPath: '/audio/system/check.mp3' },
  { itemId: 'sys_space', type: 'system', text: 'Бос орын', audioPath: '/audio/system/space.mp3' },
  { itemId: 'sys_vol_up', type: 'system', text: 'Дауысын көтеру', audioPath: '/audio/system/vol_up.mp3' },
  { itemId: 'sys_vol_down', type: 'system', text: 'Дауысын төмендету', audioPath: '/audio/system/vol_down.mp3' },
  // ==========================================
  // 1-КЕЗЕҢ: ДЫБЫСТАР / БУКВЫ (С АУДИО)
  // ==========================================
  { itemId: 'letter_ng', type: 'letter', text: 'ң', audioPath: '/audio/letters/letter_ng.mp3' },
  { itemId: 'letter_soft', type: 'letter', text: 'ь', audioPath: '/audio/letters/letter_soft.mp3' },
  { itemId: 'letter_hard', type: 'letter', text: 'ъ', audioPath: '/audio/letters/letter_hard.mp3' },
  { itemId: 'letter_yo', type: 'letter', text: 'ё', audioPath: '/audio/letters/letter_yo.mp3' },
  { itemId: 'letter_a', type: 'letter', text: 'а', audioPath: '/audio/letters/letter_a.mp3' },
  { itemId: 'letter_ae', type: 'letter', text: 'ә', audioPath: '/audio/letters/letter_ae.mp3' },
  { itemId: 'letter_b', type: 'letter', text: 'б', audioPath: '/audio/letters/letter_b.mp3' },
  { itemId: 'letter_v', type: 'letter', text: 'в', audioPath: '/audio/letters/letter_v.mp3' },
  { itemId: 'letter_g', type: 'letter', text: 'г', audioPath: '/audio/letters/letter_g.mp3' },
  { itemId: 'letter_gh', type: 'letter', text: 'ғ', audioPath: '/audio/letters/letter_gh.mp3' },
  { itemId: 'letter_d', type: 'letter', text: 'д', audioPath: '/audio/letters/letter_d.mp3' },
  { itemId: 'letter_e', type: 'letter', text: 'е', audioPath: '/audio/letters/letter_e.mp3' },
  { itemId: 'letter_zh', type: 'letter', text: 'ж', audioPath: '/audio/letters/letter_zh.mp3' },
  { itemId: 'letter_z', type: 'letter', text: 'з', audioPath: '/audio/letters/letter_z.mp3' },
  { itemId: 'letter_i', type: 'letter', text: 'и', audioPath: '/audio/letters/letter_i.mp3' },
  { itemId: 'letter_y', type: 'letter', text: 'й', audioPath: '/audio/letters/letter_y.mp3' },
  { itemId: 'letter_k', type: 'letter', text: 'к', audioPath: '/audio/letters/letter_k.mp3' },
  { itemId: 'letter_q', type: 'letter', text: 'қ', audioPath: '/audio/letters/letter_q.mp3' },
  { itemId: 'letter_l', type: 'letter', text: 'л', audioPath: '/audio/letters/letter_l.mp3' },
  { itemId: 'letter_m', type: 'letter', text: 'м', audioPath: '/audio/letters/letter_m.mp3' },
  { itemId: 'letter_n', type: 'letter', text: 'н', audioPath: '/audio/letters/letter_n.mp3' },
  { itemId: 'letter_o', type: 'letter', text: 'о', audioPath: '/audio/letters/letter_o.mp3' },
  { itemId: 'letter_oe', type: 'letter', text: 'ө', audioPath: '/audio/letters/letter_oe.mp3' },
  { itemId: 'letter_p', type: 'letter', text: 'п', audioPath: '/audio/letters/letter_p.mp3' },
  { itemId: 'letter_r', type: 'letter', text: 'р', audioPath: '/audio/letters/letter_r.mp3' },
  { itemId: 'letter_s', type: 'letter', text: 'с', audioPath: '/audio/letters/letter_s.mp3' },
  { itemId: 'letter_t', type: 'letter', text: 'т', audioPath: '/audio/letters/letter_t.mp3' },
  { itemId: 'letter_u', type: 'letter', text: 'у', audioPath: '/audio/letters/letter_u.mp3' },
  { itemId: 'letter_uh', type: 'letter', text: 'ұ', audioPath: '/audio/letters/letter_uh.mp3' },
  { itemId: 'letter_ue', type: 'letter', text: 'ү', audioPath: '/audio/letters/letter_ue.mp3' },
  { itemId: 'letter_f', type: 'letter', text: 'ф', audioPath: '/audio/letters/letter_f.mp3' },
  { itemId: 'letter_h', type: 'letter', text: 'х', audioPath: '/audio/letters/letter_h.mp3' },
  { itemId: 'letter_hh', type: 'letter', text: 'һ', audioPath: '/audio/letters/letter_hh.mp3' },
  { itemId: 'letter_c', type: 'letter', text: 'ц', audioPath: '/audio/letters/letter_c.mp3' },
  { itemId: 'letter_ch', type: 'letter', text: 'ч', audioPath: '/audio/letters/letter_ch.mp3' },
  { itemId: 'letter_sh', type: 'letter', text: 'ш', audioPath: '/audio/letters/letter_sh.mp3' },
  { itemId: 'letter_shh', type: 'letter', text: 'щ', audioPath: '/audio/letters/letter_shh.mp3' },
  { itemId: 'letter_yy', type: 'letter', text: 'ы', audioPath: '/audio/letters/letter_yy.mp3' },
  { itemId: 'letter_ii', type: 'letter', text: 'і', audioPath: '/audio/letters/letter_ii.mp3' },
  { itemId: 'letter_ee', type: 'letter', text: 'э', audioPath: '/audio/letters/letter_ee.mp3' },
  { itemId: 'letter_yu', type: 'letter', text: 'ю', audioPath: '/audio/letters/letter_yu.mp3' },
  { itemId: 'letter_ya', type: 'letter', text: 'я', audioPath: '/audio/letters/letter_ya.mp3' },

  // ==========================================
  // 2-КЕЗЕҢ: БУЫНДАР / СЛОГИ (БЕЗ АУДИО)
  // ==========================================
  { itemId: 'syl_aq', type: 'syllable', text: 'ақ' },
  { itemId: 'syl_as', type: 'syllable', text: 'ас' },
  { itemId: 'syl_aek', type: 'syllable', text: 'әк' },
  { itemId: 'syl_aen', type: 'syllable', text: 'ән' },
  { itemId: 'syl_ba', type: 'syllable', text: 'ба' },
  { itemId: 'syl_baq', type: 'syllable', text: 'бақ' },
  { itemId: 'syl_va', type: 'syllable', text: 'ва' },
  { itemId: 'syl_ven', type: 'syllable', text: 'вен' },
  { itemId: 'syl_gu', type: 'syllable', text: 'гу' },
  { itemId: 'syl_guel', type: 'syllable', text: 'гүл' },
  { itemId: 'syl_gha', type: 'syllable', text: 'ға' },
  { itemId: 'syl_ghan', type: 'syllable', text: 'ған' },
  { itemId: 'syl_do', type: 'syllable', text: 'до' },
  { itemId: 'syl_del', type: 'syllable', text: 'дел' },
  { itemId: 'syl_ek', type: 'syllable', text: 'ек' },
  { itemId: 'syl_et', type: 'syllable', text: 'ет' },
  { itemId: 'syl_zhyr', type: 'syllable', text: 'жыр' },
  { itemId: 'syl_zha', type: 'syllable', text: 'жа' },
  { itemId: 'syl_zat', type: 'syllable', text: 'зат' },
  { itemId: 'syl_zo', type: 'syllable', text: 'зо' },
  { itemId: 'syl_it', type: 'syllable', text: 'ит' },
  { itemId: 'syl_iya', type: 'syllable', text: 'ия' },
  { itemId: 'syl_yod', type: 'syllable', text: 'йод' },
  { itemId: 'syl_kon', type: 'syllable', text: 'кон' },
  { itemId: 'syl_ki', type: 'syllable', text: 'ки' },
  { itemId: 'syl_ke', type: 'syllable', text: 'ке' },
  { itemId: 'syl_qa', type: 'syllable', text: 'қа' },
  { itemId: 'syl_qon', type: 'syllable', text: 'қон' },
  { itemId: 'syl_laq', type: 'syllable', text: 'лақ' },
  { itemId: 'syl_lu', type: 'syllable', text: 'лу' },
  { itemId: 'syl_mi', type: 'syllable', text: 'ми' },
  { itemId: 'syl_maq', type: 'syllable', text: 'мақ' }, 
  { itemId: 'syl_nar', type: 'syllable', text: 'нар' },
  { itemId: 'syl_nu', type: 'syllable', text: 'ну' },
  { itemId: 'syl_or', type: 'syllable', text: 'ор' },
  { itemId: 'syl_on', type: 'syllable', text: 'он' },
  { itemId: 'syl_oer', type: 'syllable', text: 'өр' },
  { itemId: 'syl_oen', type: 'syllable', text: 'өн' },
  { itemId: 'syl_pa', type: 'syllable', text: 'па' },
  { itemId: 'syl_pin', type: 'syllable', text: 'пин' },
  { itemId: 'syl_ra', type: 'syllable', text: 'ра' },
  { itemId: 'syl_rok', type: 'syllable', text: 'рок' },
  { itemId: 'syl_sar', type: 'syllable', text: 'сар' },
  { itemId: 'syl_sot', type: 'syllable', text: 'сот' },
  { itemId: 'syl_to', type: 'syllable', text: 'то' },
  { itemId: 'syl_tar', type: 'syllable', text: 'тар' },
  { itemId: 'syl_uyq', type: 'syllable', text: 'уық' },
  { itemId: 'syl_ua', type: 'syllable', text: 'уа' },
  { itemId: 'syl_uhn', type: 'syllable', text: 'ұн' },
  { itemId: 'syl_uhl', type: 'syllable', text: 'ұл' },
  { itemId: 'syl_uey', type: 'syllable', text: 'үй' },
  { itemId: 'syl_uen', type: 'syllable', text: 'үн' },
  { itemId: 'syl_fo', type: 'syllable', text: 'фо' },
  { itemId: 'syl_fin', type: 'syllable', text: 'фин' },
  { itemId: 'syl_ha', type: 'syllable', text: 'ха' },
  { itemId: 'syl_hi', type: 'syllable', text: 'хи' },
  { itemId: 'syl_hha', type: 'syllable', text: 'һа' },
  { itemId: 'syl_ci', type: 'syllable', text: 'ци' },
  { itemId: 'syl_ca', type: 'syllable', text: 'ца' },
  { itemId: 'syl_che', type: 'syllable', text: 'че' },
  { itemId: 'syl_cho', type: 'syllable', text: 'чо' },
  { itemId: 'syl_shu', type: 'syllable', text: 'шу' },
  { itemId: 'syl_shi', type: 'syllable', text: 'ши' },
  { itemId: 'syl_shho', type: 'syllable', text: 'щё' },
  { itemId: 'syl_shha', type: 'syllable', text: 'ща' },
  { itemId: 'syl_yys', type: 'syllable', text: 'ыс' },
  { itemId: 'syl_yyq', type: 'syllable', text: 'ық' },
  { itemId: 'syl_iis', type: 'syllable', text: 'іс' },
  { itemId: 'syl_iin', type: 'syllable', text: 'ін' },
  { itemId: 'syl_ek2', type: 'syllable', text: 'эк' },
  { itemId: 'syl_oyu', type: 'syllable', text: 'ою' },
  { itemId: 'syl_uhya', type: 'syllable', text: 'ұя' },

  // ==========================================
  // 3-КЕЗЕҢ: СӨЗДЕР / СЛОВА (БЕЗ АУДИО)
  // ==========================================
  { itemId: 'word_ana', type: 'word', text: 'ана' },
  { itemId: 'word_alma', type: 'word', text: 'алма' },
  { itemId: 'word_almurt', type: 'word', text: 'алмұрт' },
  { itemId: 'word_aqyldy', type: 'word', text: 'ақылды' },
  { itemId: 'word_aeke', type: 'word', text: 'әке' },
  { itemId: 'word_aezhe', type: 'word', text: 'әже' },
  { itemId: 'word_aedemi', type: 'word', text: 'әдемі' },
  { itemId: 'word_aedepti', type: 'word', text: 'әдепті' },
  { itemId: 'word_bas', type: 'word', text: 'бас' },
  { itemId: 'word_bala', type: 'word', text: 'бала' },
  { itemId: 'word_baqsha', type: 'word', text: 'бақша' },
  { itemId: 'word_batyl', type: 'word', text: 'батыл' },
  { itemId: 'word_vagon', type: 'word', text: 'вагон' },
  { itemId: 'word_valyuta', type: 'word', text: 'валюта' },
  { itemId: 'word_virus', type: 'word', text: 'вирус' },
  { itemId: 'word_gaz', type: 'word', text: 'газ' },
  { itemId: 'word_gauhar', type: 'word', text: 'гауһар' },
  { itemId: 'word_gazeta', type: 'word', text: 'газета' },
  { itemId: 'word_guel', type: 'word', text: 'гүл' },
  { itemId: 'word_ghashyq', type: 'word', text: 'ғашық' },
  { itemId: 'word_gharysh', type: 'word', text: 'ғарыш' },
  { itemId: 'word_ghazhap', type: 'word', text: 'ғажап' },
  { itemId: 'word_ghulama', type: 'word', text: 'ғұлама' },
  { itemId: 'word_dala', type: 'word', text: 'дала' },
  { itemId: 'word_dos', type: 'word', text: 'дос' },
  { itemId: 'word_dana', type: 'word', text: 'дана' },
  { itemId: 'word_daestuer', type: 'word', text: 'дәстүр' },
  { itemId: 'word_el', type: 'word', text: 'ел' },
  { itemId: 'word_etik', type: 'word', text: 'етік' },
  { itemId: 'word_engbek', type: 'word', text: 'еңбек' },
  { itemId: 'word_erlik', type: 'word', text: 'ерлік' },
  { itemId: 'word_zhol', type: 'word', text: 'жол' },
  { itemId: 'word_zhyl', type: 'word', text: 'жыл' },
  { itemId: 'word_zhumys', type: 'word', text: 'жұмыс' },
  { itemId: 'word_zhauap', type: 'word', text: 'жауап' },
  { itemId: 'word_zang', type: 'word', text: 'заң' },
  { itemId: 'word_zaman', type: 'word', text: 'заман' },
  { itemId: 'word_zerek', type: 'word', text: 'зерек' },
  { itemId: 'word_ziyat', type: 'word', text: 'зият' },
  { itemId: 'word_it', type: 'word', text: 'ит' },
  { itemId: 'word_ine', type: 'word', text: 'ине' },
  { itemId: 'word_igilik', type: 'word', text: 'игілік' },
  { itemId: 'word_ikem', type: 'word', text: 'икем' },
  { itemId: 'word_yod', type: 'word', text: 'йод' },
  { itemId: 'word_yoga', type: 'word', text: 'йога' },
  { itemId: 'word_yogurt', type: 'word', text: 'йогурт' },
  { itemId: 'word_koel', type: 'word', text: 'көл' },
  { itemId: 'word_kitap', type: 'word', text: 'кітап' },
  { itemId: 'word_koemek', type: 'word', text: 'көмек' },
  { itemId: 'word_kaesip', type: 'word', text: 'кәсіп' },
  { itemId: 'word_qyz', type: 'word', text: 'қыз' },
  { itemId: 'word_qala', type: 'word', text: 'қала' },
  { itemId: 'word_qazyna', type: 'word', text: 'қазына' },
  { itemId: 'word_qabilet', type: 'word', text: 'қабілет' },
  { itemId: 'word_laq', type: 'word', text: 'лақ' },
  { itemId: 'word_limon', type: 'word', text: 'лимон' },
  { itemId: 'word_layyq', type: 'word', text: 'лайық' },
  { itemId: 'word_logika', type: 'word', text: 'логика' },
  { itemId: 'word_mal', type: 'word', text: 'мал' },
  { itemId: 'word_mektep', type: 'word', text: 'мектеп' },
  { itemId: 'word_meyir', type: 'word', text: 'мейір' },
  { itemId: 'word_myqty', type: 'word', text: 'мықты' },
  { itemId: 'word_nan', type: 'word', text: 'нан' },
  { itemId: 'word_naezik', type: 'word', text: 'нәзік' },
  { itemId: 'word_naghyz', type: 'word', text: 'нағыз' },
  { itemId: 'word_namys', type: 'word', text: 'намыс' },
  { itemId: 'word_nur', type: 'word', text: 'нұр' },
  { itemId: 'word_noel', type: 'word', text: 'нөл' },
  { itemId: 'word_neke', type: 'word', text: 'неке' },
  { itemId: 'word_neshe', type: 'word', text: 'неше' },
  { itemId: 'word_ot', type: 'word', text: 'от' },
  { itemId: 'word_oryn', type: 'word', text: 'орын' },
  { itemId: 'word_oqushy', type: 'word', text: 'оқушы' },
  { itemId: 'word_oynaq', type: 'word', text: 'ойнақ' },
  { itemId: 'word_oqu', type: 'word', text: 'оқу' },
  { itemId: 'word_otau', type: 'word', text: 'отау' },
  { itemId: 'word_oyyn', type: 'word', text: 'ойын' },
  { itemId: 'word_oet', type: 'word', text: 'өт' },
  { itemId: 'word_oezen', type: 'word', text: 'өзен' },
  { itemId: 'word_oemir', type: 'word', text: 'өмір' },
  { itemId: 'word_oener', type: 'word', text: 'өнер' },
  { itemId: 'word_patsha', type: 'word', text: 'патша' },
  { itemId: 'word_pikir', type: 'word', text: 'пікір' },
  { itemId: 'word_pana', type: 'word', text: 'пана' },
  { itemId: 'word_ruh', type: 'word', text: 'рух' },
  { itemId: 'word_roel', type: 'word', text: 'рөл' },
  { itemId: 'word_ras', type: 'word', text: 'рас' },
  { itemId: 'word_riza', type: 'word', text: 'риза' },
  { itemId: 'word_su', type: 'word', text: 'су' },
  { itemId: 'word_soez', type: 'word', text: 'сөз' },
  { itemId: 'word_sana', type: 'word', text: 'сана' },
  { itemId: 'word_suret', type: 'word', text: 'сурет' },
  { itemId: 'word_sabaq', type: 'word', text: 'сабақ' },
  { itemId: 'word_tas', type: 'word', text: 'тас' },
  { itemId: 'word_til', type: 'word', text: 'тіл' },
  { itemId: 'word_tau', type: 'word', text: 'тау' },
  { itemId: 'word_tuen', type: 'word', text: 'түн' },
  { itemId: 'word_tamaq', type: 'word', text: 'тамақ' },
  { itemId: 'word_u', type: 'word', text: 'у' },
  { itemId: 'word_uaq', type: 'word', text: 'уақ' },
  { itemId: 'word_uaqyt', type: 'word', text: 'уақыт' },
  { itemId: 'word_uhl', type: 'word', text: 'ұл' },
  { itemId: 'word_uhn', type: 'word', text: 'ұн' },
  { itemId: 'word_uhyat', type: 'word', text: 'ұят' },
  { itemId: 'word_uhmyt', type: 'word', text: 'ұмыт' },
  { itemId: 'word_uey', type: 'word', text: 'үй' },
  { itemId: 'word_uen', type: 'word', text: 'үн' },
  { itemId: 'word_uemit', type: 'word', text: 'үміт' },
  { itemId: 'word_fakt', type: 'word', text: 'факт' },
  { itemId: 'word_forma', type: 'word', text: 'форма' },
  { itemId: 'word_hat', type: 'word', text: 'хат' },
  { itemId: 'word_halyq', type: 'word', text: 'халық' },
  { itemId: 'word_hhaem', type: 'word', text: 'һәм' },
  { itemId: 'word_qahharman', type: 'word', text: 'қаһарман' },
  { itemId: 'word_shay', type: 'word', text: 'шай' },
  { itemId: 'word_shang', type: 'word', text: 'шаң' },
  { itemId: 'word_shoep', type: 'word', text: 'шөп' },
  { itemId: 'word_shyn', type: 'word', text: 'шын' },
  { itemId: 'word_ydys', type: 'word', text: 'ыдыс' },
  { itemId: 'word_yrys', type: 'word', text: 'ырыс' },
  { itemId: 'word_yrghaq', type: 'word', text: 'ырғақ' },
  { itemId: 'word_iis', type: 'word', text: 'іс' },
  { itemId: 'word_iini', type: 'word', text: 'іні' },
  { itemId: 'word_iilim', type: 'word', text: 'ілім' },
  { itemId: 'word_iilgek', type: 'word', text: 'ілгек' },
  { itemId: 'word_iilgish', type: 'word', text: 'ілгіш' },
  { itemId: 'word_ekran', type: 'word', text: 'экран' },
  { itemId: 'word_ekipazh', type: 'word', text: 'экипаж' },
  { itemId: 'word_yurist', type: 'word', text: 'юрист' },
  { itemId: 'word_ayu', type: 'word', text: 'аю' },
  { itemId: 'word_qoyu', type: 'word', text: 'қою' },
  { itemId: 'word_sueyu', type: 'word', text: 'сүю' },
  { itemId: 'word_eseyu', type: 'word', text: 'есею' },
  { itemId: 'word_yadro', type: 'word', text: 'ядро' },
  { itemId: 'word_yaghni', type: 'word', text: 'яғни' }
];

const importData = async () => {
  try {
    await connectDB();

    // Алдымен ескі мәліметтерді тазалаймыз
    await GameItem.deleteMany();
    console.log('Старые данные удалены.');

    // Жаңа мәліметтерді саламыз
    await GameItem.insertMany(gameItemsData);
    console.log('Все 100% данных (дыбыстар, буындар, сөздер) успешно импортированы в MongoDB!');

    process.exit();
  } catch (error) {
    console.error(`Ошибка при импорте: ${error.message}`);
    process.exit(1);
  }
};

importData();